disabled_rules:
  - colon
  - comma
  - control_statement
opt_in_rules:
  - empty_count
analyzer_rules:
  - explicit_self
included:
  - "*/*.swift"
  - "*/**/*.swift"
excluded:
  - "*.xcodeproj"
  - ".git"
  - Pods
allow_zero_lintable_files: false
strict: false
lenient: false
baseline: Baseline.json
write_baseline: Baseline.json
check_for_updates: true
force_cast: warning
force_try:
  severity: warning
line_length: 110
type_body_length:
  - 300
  - 400
file_length:
  warning: 500
  error: 1200
type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
  allowed_symbols: ["_"] 
identifier_name:
  min_length:
    error: 4
  excluded:
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode"
