name: Africa
options:
  bundleIdPrefix: br.com.tsabian.app.ios
  deploymentTarget:
    iOS: '17.2'
    macOS: '13.6'
  indentWidth: 2
  tabWidth: 2
settings:
  GENERATE_INFOPLIST_FILE: NO
configurations:
  Debug:
    buildSettings:
      ALWAYS_SEARCH_USER_PATHS: NO
      ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
      CLANG_ANALYZER_NONNULL: YES
      CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION: YES_AGGRESSIVE
      CLANG_CXX_LANGUAGE_STANDARD: gnu++20
      CLANG_ENABLE_MODULES: YES
      CLANG_ENABLE_OBJC_ARC: YES
      CLANG_ENABLE_OBJC_WEAK: YES
      CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: YES
      CLANG_WARN_BOOL_CONVERSION: YES
      CLANG_WARN_COMMA: YES
      CLANG_WARN_CONSTANT_CONVERSION: YES
      CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: YES
      CLANG_WARN_DIRECT_OBJC_ISA_USAGE: YES_ERROR
      CLANG_WARN_DOCUMENTATION_COMMENTS: YES
      CLANG_WARN_EMPTY_BODY: YES
      CLANG_WARN_ENUM_CONVERSION: YES
      CLANG_WARN_INFINITE_RECURSION: YES
      CLANG_WARN_INT_CONVERSION: YES
      CLANG_WARN_NON_LITERAL_NULL_CONVERSION: YES
      CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: YES
      CLANG_WARN_OBJC_LITERAL_CONVERSION: YES
      CLANG_WARN_OBJC_ROOT_CLASS: YES_ERROR
      CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: YES
      CLANG_WARN_RANGE_LOOP_ANALYSIS: YES
      CLANG_WARN_STRICT_PROTOTYPES: YES
      CLANG_WARN_SUSPICIOUS_MOVE: YES
      CLANG_WARN_UNGUARDED_AVAILABILITY: YES_AGGRESSIVE
      CLANG_WARN_UNREACHABLE_CODE: YES
      CLANG_WARN__DUPLICATE_METHOD_MATCH: YES
      COPY_PHASE_STRIP: NO
      DEBUG_INFORMATION_FORMAT: dwarf
      ENABLE_STRICT_OBJC_MSGSEND: YES
      ENABLE_TESTABILITY: YES
      ENABLE_USER_SCRIPT_SANDBOXING: YES
      GCC_C_LANGUAGE_STANDARD: gnu17
      GCC_DYNAMIC_NO_PIC: NO
      GCC_NO_COMMON_BLOCKS: YES
      GCC_OPTIMIZATION_LEVEL: 0
      GCC_PREPROCESSOR_DEFINITIONS:
        - DEBUG=1
        - $(inherited)
      GCC_WARN_64_TO_32_BIT_CONVERSION: YES
      GCC_WARN_ABOUT_RETURN_TYPE: YES_ERROR
      GCC_WARN_UNDECLARED_SELECTOR: YES
      GCC_WARN_UNINITIALIZED_AUTOS: YES_AGGRESSIVE
      GCC_WARN_UNUSED_FUNCTION: YES
      GCC_WARN_UNUSED_VARIABLE: YES
      LOCALIZATION_PREFERS_STRING_CATALOGS: YES
      MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
      MTL_FAST_MATH: YES
      ONLY_ACTIVE_ARCH: YES
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG $(inherited)
      SWIFT_OPTIMIZATION_LEVEL: -Onone
  Release:
    buildSettings:
      ALWAYS_SEARCH_USER_PATHS: NO
      ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
      CLANG_ANALYZER_NONNULL: YES
      CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION: YES_AGGRESSIVE
      CLANG_CXX_LANGUAGE_STANDARD: gnu++20
      CLANG_ENABLE_MODULES: YES
      CLANG_ENABLE_OBJC_ARC: YES
      CLANG_ENABLE_OBJC_WEAK: YES
      CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: YES
      CLANG_WARN_BOOL_CONVERSION: YES
      CLANG_WARN_COMMA: YES
      CLANG_WARN_CONSTANT_CONVERSION: YES
      CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: YES
      CLANG_WARN_DIRECT_OBJC_ISA_USAGE: YES_ERROR
      CLANG_WARN_DOCUMENTATION_COMMENTS: YES
      CLANG_WARN_EMPTY_BODY: YES
      CLANG_WARN_ENUM_CONVERSION: YES
      CLANG_WARN_INFINITE_RECURSION: YES
      CLANG_WARN_INT_CONVERSION: YES
      CLANG_WARN_NON_LITERAL_NULL_CONVERSION: YES
      CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: YES
      CLANG_WARN_OBJC_LITERAL_CONVERSION: YES
      CLANG_WARN_OBJC_ROOT_CLASS: YES_ERROR
      CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: YES
      CLANG_WARN_RANGE_LOOP_ANALYSIS: YES
      CLANG_WARN_STRICT_PROTOTYPES: YES
      CLANG_WARN_SUSPICIOUS_MOVE: YES
      CLANG_WARN_UNGUARDED_AVAILABILITY: YES_AGGRESSIVE
      CLANG_WARN_UNREACHABLE_CODE: YES
      CLANG_WARN__DUPLICATE_METHOD_MATCH: YES
      COPY_PHASE_STRIP: NO
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      ENABLE_NS_ASSERTIONS: NO
      ENABLE_STRICT_OBJC_MSGSEND: YES
      ENABLE_USER_SCRIPT_SANDBOXING: YES
      GCC_C_LANGUAGE_STANDARD: gnu17
      GCC_NO_COMMON_BLOCKS: YES
      GCC_WARN_64_TO_32_BIT_CONVERSION: YES
      GCC_WARN_ABOUT_RETURN_TYPE: YES_ERROR
      GCC_WARN_UNDECLARED_SELECTOR: YES
      GCC_WARN_UNINITIALIZED_AUTOS: YES_AGGRESSIVE
      GCC_WARN_UNUSED_FUNCTION: YES
      GCC_WARN_UNUSED_VARIABLE: YES
      LOCALIZATION_PREFERS_STRING_CATALOGS: YES
      MTL_ENABLE_DEBUG_INFO: NO
      MTL_FAST_MATH: YES
      SWIFT_COMPILATION_MODE: wholemodule
settings:
  GENERATE_INFOPLIST_FILE: NO
targets:
  Africa:
    info:
      path: Africa/Info.plist
      properties:
        CFBundleDisplayName: Africa
        CFBundleShortVersionString: 1.0
        CFBundleVersion: 1
    type: application
    platform: iOS
    sources: Africa
    resources:
      - Africa/Assets.xcassets
      - Africa/Preview\ Assets.xcassets
      - Africa/Video
    dependencies:
      - target: AfricaTests
      - target: AfricaUITests
    postBuildScripts:
      - path: Scripts/lint.sh
        name: "[Run] SwiftLint"
        basedOnDependencyAnalysis: false
      - path: Scripts/format.sh
        name: "[Run] Swiftformat"
        basedOnDependencyAnalysis: false
  AfricaTests:
    type: bundle.unit-test
    platform: iOS
    sources: AfricaTests
    dependencies:
      - target: Africa
    postBuildScripts:
      - path: Scripts/lint.sh
        name: "[Run] SwiftLint"
        basedOnDependencyAnalysis: false
      - path: Scripts/format.sh
        name: "[Run] Swiftformat"
        basedOnDependencyAnalysis: false
  AfricaUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: AfricaUITests
    dependencies:
      - target: Africa
    postBuildScripts:
      - path: Scripts/lint.sh
        name: "[Run] SwiftLint"
        basedOnDependencyAnalysis: false
      - path: Scripts/format.sh
        name: "[Run] Swiftformat"
        basedOnDependencyAnalysis: false